---
title: "Developing Data Products Course Project"
author: "Manohar Reddy"
date: "November 6, 2016"
output: slidy_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Course Project

The application uses the mtcars data from the R datasets package, and allows users to see a box-plot that explores the relationship between miles-per-gallon (MPG) and three other variables (Cylinders, Transmission, and Gears).

The user can select any variable and can select the outliers checkbox.

## ui.R
```{r cars, echo = TRUE, eval=FALSE}
library(shiny)

# Define UI for miles per gallon application
shinyUI(pageWithSidebar(
  
  # Application title
  headerPanel("Miles Per Gallon"),
  
  # Sidebar with controls to select the variable to plot against mpg
  # and to specify whether outliers should be included
  sidebarPanel(
    selectInput("variable", "Variable:",
                list("Cylinders" = "cyl", 
                     "Transmission" = "am", 
                     "Gears" = "gear")),
    
    checkboxInput("outliers", "Show outliers", FALSE)
  ),
  
  # Show the caption and plot of the requested variable against mpg
  mainPanel(
    h3(textOutput("caption")),
    
    plotOutput("mpgPlot")
  )
))
```
## server.R
```{r echo = TRUE, eval=FALSE}
library("shiny")
library("datasets")
library("ggplot2")

# We tweak the "am" field to have nicer factor labels. Since this doesn't
# rely on any user inputs we can do this once at startup and then use the
# value throughout the lifetime of the application
mpgData <- mtcars
mpgData$am <- factor(mpgData$am, labels = c("Automatic", "Manual"))

# Define server logic required to plot various variables against mpg
shinyServer(function(input, output) {
  
  # Compute the forumla text in a reactive expression since it is
  # shared by the output$caption and output$mpgPlot expressions
  formulaText <- reactive({
    paste("mpg ~", input$variable)
  })
  
  # Return the formula text for printing as a caption
  output$caption <- renderText({
    formulaText()
  })
  
  # Generate a plot of the requested variable against mpg and only
  # include outliers if requested
  # ggplot version
  output$mpgPlot <- renderPlot({
    
    # check for the input variable
    if (input$variable == "am") {
      # am
      mpgData <- data.frame(mpg = mtcars$mpg, 
                            var = factor(mtcars[[input$variable]], 
                                         labels = c("Automatic", "Manual")))
    }
    else {
      # cyl and gear
      mpgData <- data.frame(mpg = mtcars$mpg, var = factor(mtcars[[input$variable]]))
    }
    
    p <- ggplot(mpgData, aes(var, mpg)) +
      geom_boxplot(outlier.size = ifelse(input$outliers, 2, NA)) +
      xlab(input$variable)
    print(p)
    
  })
})
```


## Box Plot (mpg ~ cylinders)
```{r echo = TRUE, eval=TRUE}
library(ggplot2)
mpgData <- data.frame(mpg = mtcars$mpg, var = factor(mtcars$cyl))
ggplot(mpgData, aes(var, mpg)) +
      geom_boxplot(outlier.size = 2) + xlab("cyl")


```